name: ci lesson
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        # default: 'dev'
        description: 'dev,stg,prd'
        required: true
jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    timeout-minutes: 5
    steps:
      - run: echo ${{ secrets.TEST_ENV }}
